### ISSUE TITLE
URL for download and use

### ISSUE THREAD

**Issue by jeremyb31** [UbuntuForums/system-info#1]
It is now wget -N -t 5 -T 10 https://github.com/Mafoelffen1/system-info/raw/main/system-info && \
chmod +x system-info && \
./support-info
but shouldn't it be 
wget -N -t 5 -T 10 https://github.com/UbuntuForums/system-info/raw/main/system-info && \
chmod +x system-info && \
./support-info
When it is here?

**Comment by Mafoelffen1** [comment]
Yes... Updating that now... Had to create a hack in my GitHub Repo to update this file AND finding that updating this file is VERY picky about one-liner scripts... and some kind of invisible extraneous characters if edited within the online GitHub Editor.

I'll PM you later today on those.

**Comment by Mafoelffen1** [comment]
Updated. That also fixed some spelling errors. Still need to PM you after an other appointment today...

Thank you.
