### ISSUE TITLE
Correction to spelling

### ISSUE THREAD

**Issue by ghost** [UbuntuForums/system-info#3]
Lines 488, 489 and 490
`Adress` > `Address`

**Comment by Mafoelffen1** [comment]
I believe this has been taken care of while we were doing testing before the final release...

**Comment by Mafoelffen1** [comment]
I have to look at that version of the code at that date to confirm...

**Comment by Mafoelffen1** [comment]
Dang. I wish he had quoted the misspelling. I would think that would be in an echo'ed prompt... and I don't see any more mispelling's in that now. sudodus hit me hard to correct what he and Doug S found.

**Comment by Mafoelffen1** [comment]
Found all three. Tahnk you.

**Comment by Mafoelffen1** [comment]
Dang. LOL. Thank you. Should spell the comment correctly right? LOL
